# CMake generated Testfile for 
# Source directory: ${CTEST_SOURCE_DIRECTORY}/RTI13/fddget
# Build directory: ${CTEST_SOURCE_DIRECTORY}/RTI13/fddget
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
# SET(CTEST_BINARY_DIRECTORY "D:/vfs/CANoe/private/mth/12.0_DistSim_HLA/bin/Exec32_Debug")
add_test(rti13/fddget-13-1 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-1.fed" "-o" "objectRoot" "-a" "privilegeToDelete" "-i" "interactionRoot")
add_test(rti13/fddget-13-2 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-1.fed" "-o" "ObjectClass1" "-a" "privilegeToDelete" "-a" "Attribute1" "-i" "InteractionClass1" "-p" "Parameter1")
add_test(rti13/fddget-13-3 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-1.fed" "-o" "objectRoot.ObjectClass1" "-a" "privilegeToDelete" "-a" "objectRoot.ObjectClass1.Attribute1" "-i" "interactionRoot.InteractionClass1" "-p" "interactionRoot.InteractionClass1.Parameter1")
add_test(rti13/fddget-13-4 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-1.fed" "-o" "ObjectClass2" "-a" "privilegeToDelete" "-a" "Attribute1" "-a" "Attribute2" "-i" "InteractionClass2" "-p" "Parameter1" "-p" "Parameter2")
add_test(rti13/fddget-13-5 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-1.fed" "-o" "objectRoot.ObjectClass1.ObjectClass2" "-a" "privilegeToDelete" "-a" "objectRoot.ObjectClass1.Attribute1" "-a" "objectRoot.ObjectClass1.ObjectClass2.Attribute2" "-i" "interactionRoot.InteractionClass1.InteractionClass2" "-p" "interactionRoot.InteractionClass1.Parameter1" "-p" "interactionRoot.InteractionClass1.InteractionClass2.Parameter2")
add_test(rti13/fddget-13-6 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-1.fed" "-o" "ObjectClass3" "-a" "privilegeToDelete" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
add_test(rti13/fddget-13-7 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-1.fed" "-o" "objectRoot.ObjectClass3" "-a" "privilegeToDelete" "-a" "objectRoot.ObjectClass3.Attribute3" "-i" "interactionRoot.InteractionClass3" "-p" "interactionRoot.InteractionClass3.Parameter3")
add_test(rti13/fddget-13-11 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "objectRoot" "-a" "privilegeToDelete" "-i" "interactionRoot")
add_test(rti13/fddget-13-12 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "ObjectClass1" "-a" "privilegeToDelete" "-a" "Attribute1" "-i" "InteractionClass1" "-p" "Parameter1")
add_test(rti13/fddget-13-13 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "ObjectClass1" "-a" "privilegeToDelete" "-a" "ObjectClass1.Attribute1" "-i" "InteractionClass1" "-p" "InteractionClass1.Parameter1")
add_test(rti13/fddget-13-14 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "ObjectClass2" "-a" "privilegeToDelete" "-a" "Attribute1" "-a" "Attribute2" "-i" "InteractionClass2" "-p" "Parameter1" "-p" "Parameter2")
add_test(rti13/fddget-13-15 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "ObjectClass1.ObjectClass2" "-a" "privilegeToDelete" "-a" "ObjectClass1.Attribute1" "-a" "ObjectClass1.ObjectClass2.Attribute2" "-i" "InteractionClass1.InteractionClass2" "-p" "InteractionClass1.Parameter1" "-p" "InteractionClass1.InteractionClass2.Parameter2")
add_test(rti13/fddget-13-16 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "ObjectClass3" "-a" "privilegeToDelete" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
add_test(rti13/fddget-13-17 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "ObjectClass3" "-a" "privilegeToDelete" "-a" "ObjectClass3.Attribute3" "-i" "InteractionClass3" "-p" "InteractionClass3.Parameter3")
add_test(rti13/fddget-13-20 "${CTEST_BINARY_DIRECTORY}/fddget-13" "-D" "-O" "${CTEST_SOURCE_DIRECTORY}/RTI13/fddget/fdd-2.fed" "-o" "ObjectClass3" "-a" "privilegeToDelete" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
