
// Code automatically generated by T4 template from D:\vfs\CANoe\release\15.2\Projects_Source\OpenRTI-master\tests\rti1516ev\codegen\\mom.xml, do not edit
#pragma once

#include <vector>
#include <functional>

#include "RTI/encoding/HLAhandle.h"
#include "RTI/encoding/HLAopaqueData.h"
#include "momEncodings.h"

namespace OpenRTI {
namespace Mom {

class IHLAobjectRoot;
class IHLAobjectRootObjectClass
{
  public:
    virtual void Publish() = 0;
    virtual void Unpublish() = 0;
    virtual void Subscribe() = 0;
    virtual void Unsubscribe() = 0;
    virtual IHLAobjectRoot* GetObjectInstance(const std::wstring& instanceName) = 0;
    virtual IHLAobjectRoot* CreateObjectInstance(const std::wstring& instanceName) = 0;
};

class IHLAobjectRoot
{
  public:
    using AttributeBits = uint32_t;
    static const AttributeBits kNone = 0x0;
    static const AttributeBits kHLAprivilegeToDeleteObjectBit = 0x1;

    IHLAobjectRoot() {}
    virtual ~IHLAobjectRoot() {}
    IHLAobjectRoot(const IHLAobjectRoot&) = delete;
    IHLAobjectRoot(IHLAobjectRoot&&) = delete;
    IHLAobjectRoot& operator=(const IHLAobjectRoot&) = delete;
    IHLAobjectRoot& operator=(IHLAobjectRoot&&) = delete;

    virtual std::wstring GetObjectInstanceName() const = 0;
    // attribute HLAprivilegeToDeleteObject : HLAtoken
    virtual const std::vector<uint8_t>& GetHLAprivilegeToDeleteObject() const = 0;
    virtual void SetHLAprivilegeToDeleteObject(std::vector<uint8_t> newValue) = 0;
};

class IHLAmanager;
class IHLAmanagerObjectClass
{
  public:
    virtual void Publish() = 0;
    virtual void Unpublish() = 0;
    virtual void Subscribe() = 0;
    virtual void Unsubscribe() = 0;
    virtual IHLAmanager* GetObjectInstance(const std::wstring& instanceName) = 0;
    virtual IHLAmanager* CreateObjectInstance(const std::wstring& instanceName) = 0;
};

class IHLAmanager : public IHLAobjectRoot
{
  public:

    IHLAmanager() {}
    ~IHLAmanager() {}
    IHLAmanager(const IHLAmanager&) = delete;
    IHLAmanager(IHLAmanager&&) = delete;
    IHLAmanager& operator=(const IHLAmanager&) = delete;
    IHLAmanager& operator=(IHLAmanager&&) = delete;

};

class IHLAfederate;
class IHLAfederateObjectClass
{
  public:
    virtual void Publish() = 0;
    virtual void Unpublish() = 0;
    virtual void Subscribe() = 0;
    virtual void Unsubscribe() = 0;
    virtual IHLAfederate* GetObjectInstance(const std::wstring& instanceName) = 0;
    virtual IHLAfederate* CreateObjectInstance(const std::wstring& instanceName) = 0;
};

class IHLAfederate : public IHLAmanager
{
  public:
    static const AttributeBits kHLAfederateHandleBit = 0x2;
    static const AttributeBits kHLAfederateNameBit = 0x4;
    static const AttributeBits kHLAfederateTypeBit = 0x8;
    static const AttributeBits kHLAfederateHostBit = 0x10;
    static const AttributeBits kHLARTIversionBit = 0x20;
    static const AttributeBits kHLAFOMmoduleDesignatorListBit = 0x40;
    static const AttributeBits kHLAtimeConstrainedBit = 0x80;
    static const AttributeBits kHLAtimeRegulatingBit = 0x100;
    static const AttributeBits kHLAasynchronousDeliveryBit = 0x200;
    static const AttributeBits kHLAfederateStateBit = 0x400;
    static const AttributeBits kHLAtimeManagerStateBit = 0x800;
    static const AttributeBits kHLAlogicalTimeBit = 0x1000;
    static const AttributeBits kHLAlookaheadBit = 0x2000;
    static const AttributeBits kHLAGALTBit = 0x4000;
    static const AttributeBits kHLALITSBit = 0x8000;
    static const AttributeBits kHLAROlengthBit = 0x10000;
    static const AttributeBits kHLATSOlengthBit = 0x20000;
    static const AttributeBits kHLAreflectionsReceivedBit = 0x40000;
    static const AttributeBits kHLAupdatesSentBit = 0x80000;
    static const AttributeBits kHLAinteractionsReceivedBit = 0x100000;
    static const AttributeBits kHLAinteractionsSentBit = 0x200000;
    static const AttributeBits kHLAobjectInstancesThatCanBeDeletedBit = 0x400000;
    static const AttributeBits kHLAobjectInstancesUpdatedBit = 0x800000;
    static const AttributeBits kHLAobjectInstancesReflectedBit = 0x1000000;
    static const AttributeBits kHLAobjectInstancesDeletedBit = 0x2000000;
    static const AttributeBits kHLAobjectInstancesRemovedBit = 0x4000000;
    static const AttributeBits kHLAobjectInstancesRegisteredBit = 0x8000000;
    static const AttributeBits kHLAobjectInstancesDiscoveredBit = 0x10000000;
    static const AttributeBits kHLAtimeGrantedTimeBit = 0x20000000;
    static const AttributeBits kHLAtimeAdvancingTimeBit = 0x40000000;
    static const AttributeBits kHLAconveyRegionDesignatorSetsBit = 0x80000000;
    static const AttributeBits kHLAconveyProducingFederateBit = 0x100000000;

    IHLAfederate() {}
    ~IHLAfederate() {}
    IHLAfederate(const IHLAfederate&) = delete;
    IHLAfederate(IHLAfederate&&) = delete;
    IHLAfederate& operator=(const IHLAfederate&) = delete;
    IHLAfederate& operator=(IHLAfederate&&) = delete;

    // attribute HLAfederateHandle : HLAhandle
    virtual rti1516ev::HLAhandle GetHLAfederateHandle() const = 0;
    virtual void SetHLAfederateHandle(rti1516ev::HLAhandle newValue) = 0;
    // attribute HLAfederateName : HLAunicodeString
    virtual std::wstring GetHLAfederateName() const = 0;
    virtual void SetHLAfederateName(std::wstring newValue) = 0;
    // attribute HLAfederateType : HLAunicodeString
    virtual std::wstring GetHLAfederateType() const = 0;
    virtual void SetHLAfederateType(std::wstring newValue) = 0;
    // attribute HLAfederateHost : HLAunicodeString
    virtual std::wstring GetHLAfederateHost() const = 0;
    virtual void SetHLAfederateHost(std::wstring newValue) = 0;
    // attribute HLARTIversion : HLAunicodeString
    virtual std::wstring GetHLARTIversion() const = 0;
    virtual void SetHLARTIversion(std::wstring newValue) = 0;
    // attribute HLAFOMmoduleDesignatorList : HLAmoduleDesignatorList
    virtual const std::vector<std::wstring>& GetHLAFOMmoduleDesignatorList() const = 0;
    virtual void SetHLAFOMmoduleDesignatorList(std::vector<std::wstring> newValue) = 0;
    // attribute HLAtimeConstrained : HLAboolean
    virtual bool GetHLAtimeConstrained() const = 0;
    virtual void SetHLAtimeConstrained(bool newValue) = 0;
    // attribute HLAtimeRegulating : HLAboolean
    virtual bool GetHLAtimeRegulating() const = 0;
    virtual void SetHLAtimeRegulating(bool newValue) = 0;
    // attribute HLAasynchronousDelivery : HLAboolean
    virtual bool GetHLAasynchronousDelivery() const = 0;
    virtual void SetHLAasynchronousDelivery(bool newValue) = 0;
    // attribute HLAfederateState : HLAfederateState
    virtual HLAfederateState GetHLAfederateState() const = 0;
    virtual void SetHLAfederateState(HLAfederateState newValue) = 0;
    // attribute HLAtimeManagerState : HLAtimeState
    virtual HLAtimeState GetHLAtimeManagerState() const = 0;
    virtual void SetHLAtimeManagerState(HLAtimeState newValue) = 0;
    // attribute HLAlogicalTime : HLAlogicalTime
    virtual const std::vector<uint8_t>& GetHLAlogicalTime() const = 0;
    virtual void SetHLAlogicalTime(std::vector<uint8_t> newValue) = 0;
    // attribute HLAlookahead : HLAtimeInterval
    virtual const std::vector<uint8_t>& GetHLAlookahead() const = 0;
    virtual void SetHLAlookahead(std::vector<uint8_t> newValue) = 0;
    // attribute HLAGALT : HLAlogicalTime
    virtual const std::vector<uint8_t>& GetHLAGALT() const = 0;
    virtual void SetHLAGALT(std::vector<uint8_t> newValue) = 0;
    // attribute HLALITS : HLAlogicalTime
    virtual const std::vector<uint8_t>& GetHLALITS() const = 0;
    virtual void SetHLALITS(std::vector<uint8_t> newValue) = 0;
    // attribute HLAROlength : HLAcount
    virtual HLAcount GetHLAROlength() const = 0;
    virtual void SetHLAROlength(HLAcount newValue) = 0;
    // attribute HLATSOlength : HLAcount
    virtual HLAcount GetHLATSOlength() const = 0;
    virtual void SetHLATSOlength(HLAcount newValue) = 0;
    // attribute HLAreflectionsReceived : HLAcount
    virtual HLAcount GetHLAreflectionsReceived() const = 0;
    virtual void SetHLAreflectionsReceived(HLAcount newValue) = 0;
    // attribute HLAupdatesSent : HLAcount
    virtual HLAcount GetHLAupdatesSent() const = 0;
    virtual void SetHLAupdatesSent(HLAcount newValue) = 0;
    // attribute HLAinteractionsReceived : HLAcount
    virtual HLAcount GetHLAinteractionsReceived() const = 0;
    virtual void SetHLAinteractionsReceived(HLAcount newValue) = 0;
    // attribute HLAinteractionsSent : HLAcount
    virtual HLAcount GetHLAinteractionsSent() const = 0;
    virtual void SetHLAinteractionsSent(HLAcount newValue) = 0;
    // attribute HLAobjectInstancesThatCanBeDeleted : HLAcount
    virtual HLAcount GetHLAobjectInstancesThatCanBeDeleted() const = 0;
    virtual void SetHLAobjectInstancesThatCanBeDeleted(HLAcount newValue) = 0;
    // attribute HLAobjectInstancesUpdated : HLAcount
    virtual HLAcount GetHLAobjectInstancesUpdated() const = 0;
    virtual void SetHLAobjectInstancesUpdated(HLAcount newValue) = 0;
    // attribute HLAobjectInstancesReflected : HLAcount
    virtual HLAcount GetHLAobjectInstancesReflected() const = 0;
    virtual void SetHLAobjectInstancesReflected(HLAcount newValue) = 0;
    // attribute HLAobjectInstancesDeleted : HLAcount
    virtual HLAcount GetHLAobjectInstancesDeleted() const = 0;
    virtual void SetHLAobjectInstancesDeleted(HLAcount newValue) = 0;
    // attribute HLAobjectInstancesRemoved : HLAcount
    virtual HLAcount GetHLAobjectInstancesRemoved() const = 0;
    virtual void SetHLAobjectInstancesRemoved(HLAcount newValue) = 0;
    // attribute HLAobjectInstancesRegistered : HLAcount
    virtual HLAcount GetHLAobjectInstancesRegistered() const = 0;
    virtual void SetHLAobjectInstancesRegistered(HLAcount newValue) = 0;
    // attribute HLAobjectInstancesDiscovered : HLAcount
    virtual HLAcount GetHLAobjectInstancesDiscovered() const = 0;
    virtual void SetHLAobjectInstancesDiscovered(HLAcount newValue) = 0;
    // attribute HLAtimeGrantedTime : HLAmsec
    virtual HLAmsec GetHLAtimeGrantedTime() const = 0;
    virtual void SetHLAtimeGrantedTime(HLAmsec newValue) = 0;
    // attribute HLAtimeAdvancingTime : HLAmsec
    virtual HLAmsec GetHLAtimeAdvancingTime() const = 0;
    virtual void SetHLAtimeAdvancingTime(HLAmsec newValue) = 0;
    // attribute HLAconveyRegionDesignatorSets : HLAswitch
    virtual HLAswitch GetHLAconveyRegionDesignatorSets() const = 0;
    virtual void SetHLAconveyRegionDesignatorSets(HLAswitch newValue) = 0;
    // attribute HLAconveyProducingFederate : HLAswitch
    virtual HLAswitch GetHLAconveyProducingFederate() const = 0;
    virtual void SetHLAconveyProducingFederate(HLAswitch newValue) = 0;
    virtual void UpdateAllAttributeValues() = 0;
    virtual void UpdateAllAttributeValues(const rti1516ev::LogicalTime& time) = 0;
    virtual void UpdateModifiedAttributeValues() = 0;
    virtual void UpdateModifiedAttributeValues(const rti1516ev::LogicalTime& time) = 0;
    virtual AttributeBits GetUpdatedAttributes() const = 0;
    using UpdateCallbackType = std::function<void(IHLAfederate*)>;
    virtual uint32_t RegisterUpdateCallback(UpdateCallbackType callback) = 0;
    virtual void UnregisterUpdateCallback(uint32_t callbackToken) = 0;
};

class IHLAfederation;
class IHLAfederationObjectClass
{
  public:
    virtual void Publish() = 0;
    virtual void Unpublish() = 0;
    virtual void Subscribe() = 0;
    virtual void Unsubscribe() = 0;
    virtual IHLAfederation* GetObjectInstance(const std::wstring& instanceName) = 0;
    virtual IHLAfederation* CreateObjectInstance(const std::wstring& instanceName) = 0;
};

class IHLAfederation : public IHLAmanager
{
  public:
    static const AttributeBits kHLAfederationNameBit = 0x2;
    static const AttributeBits kHLAfederatesInFederationBit = 0x4;
    static const AttributeBits kHLARTIversionBit = 0x8;
    static const AttributeBits kHLAMIMdesignatorBit = 0x10;
    static const AttributeBits kHLAFOMmoduleDesignatorListBit = 0x20;
    static const AttributeBits kHLAcurrentFDDBit = 0x40;
    static const AttributeBits kHLAtimeImplementationNameBit = 0x80;
    static const AttributeBits kHLAlastSaveNameBit = 0x100;
    static const AttributeBits kHLAlastSaveTimeBit = 0x200;
    static const AttributeBits kHLAnextSaveNameBit = 0x400;
    static const AttributeBits kHLAnextSaveTimeBit = 0x800;
    static const AttributeBits kHLAautoProvideBit = 0x1000;

    IHLAfederation() {}
    ~IHLAfederation() {}
    IHLAfederation(const IHLAfederation&) = delete;
    IHLAfederation(IHLAfederation&&) = delete;
    IHLAfederation& operator=(const IHLAfederation&) = delete;
    IHLAfederation& operator=(IHLAfederation&&) = delete;

    // attribute HLAfederationName : HLAunicodeString
    virtual std::wstring GetHLAfederationName() const = 0;
    virtual void SetHLAfederationName(std::wstring newValue) = 0;
    // attribute HLAfederatesInFederation : HLAhandleList
    virtual const std::vector<rti1516ev::HLAhandle>& GetHLAfederatesInFederation() const = 0;
    virtual void SetHLAfederatesInFederation(std::vector<rti1516ev::HLAhandle> newValue) = 0;
    // attribute HLARTIversion : HLAunicodeString
    virtual std::wstring GetHLARTIversion() const = 0;
    virtual void SetHLARTIversion(std::wstring newValue) = 0;
    // attribute HLAMIMdesignator : HLAunicodeString
    virtual std::wstring GetHLAMIMdesignator() const = 0;
    virtual void SetHLAMIMdesignator(std::wstring newValue) = 0;
    // attribute HLAFOMmoduleDesignatorList : HLAmoduleDesignatorList
    virtual const std::vector<std::wstring>& GetHLAFOMmoduleDesignatorList() const = 0;
    virtual void SetHLAFOMmoduleDesignatorList(std::vector<std::wstring> newValue) = 0;
    // attribute HLAcurrentFDD : HLAunicodeString
    virtual std::wstring GetHLAcurrentFDD() const = 0;
    virtual void SetHLAcurrentFDD(std::wstring newValue) = 0;
    // attribute HLAtimeImplementationName : HLAunicodeString
    virtual std::wstring GetHLAtimeImplementationName() const = 0;
    virtual void SetHLAtimeImplementationName(std::wstring newValue) = 0;
    // attribute HLAlastSaveName : HLAunicodeString
    virtual std::wstring GetHLAlastSaveName() const = 0;
    virtual void SetHLAlastSaveName(std::wstring newValue) = 0;
    // attribute HLAlastSaveTime : HLAlogicalTime
    virtual const std::vector<uint8_t>& GetHLAlastSaveTime() const = 0;
    virtual void SetHLAlastSaveTime(std::vector<uint8_t> newValue) = 0;
    // attribute HLAnextSaveName : HLAunicodeString
    virtual std::wstring GetHLAnextSaveName() const = 0;
    virtual void SetHLAnextSaveName(std::wstring newValue) = 0;
    // attribute HLAnextSaveTime : HLAlogicalTime
    virtual const std::vector<uint8_t>& GetHLAnextSaveTime() const = 0;
    virtual void SetHLAnextSaveTime(std::vector<uint8_t> newValue) = 0;
    // attribute HLAautoProvide : HLAswitch
    virtual HLAswitch GetHLAautoProvide() const = 0;
    virtual void SetHLAautoProvide(HLAswitch newValue) = 0;
    virtual void UpdateAllAttributeValues() = 0;
    virtual void UpdateAllAttributeValues(const rti1516ev::LogicalTime& time) = 0;
    virtual void UpdateModifiedAttributeValues() = 0;
    virtual void UpdateModifiedAttributeValues(const rti1516ev::LogicalTime& time) = 0;
    virtual AttributeBits GetUpdatedAttributes() const = 0;
    using UpdateCallbackType = std::function<void(IHLAfederation*)>;
    virtual uint32_t RegisterUpdateCallback(UpdateCallbackType callback) = 0;
    virtual void UnregisterUpdateCallback(uint32_t callbackToken) = 0;
};


class IObjectClassRegistry
{
  public:
    virtual IHLAobjectRootObjectClass* GetHLAobjectRootObjectClass() const = 0;
    virtual IHLAmanagerObjectClass* GetHLAmanagerObjectClass() const = 0;
    virtual IHLAfederateObjectClass* GetHLAfederateObjectClass() const = 0;
    virtual IHLAfederationObjectClass* GetHLAfederationObjectClass() const = 0;
  protected:
    virtual ~IObjectClassRegistry() {}
}; // class IObjectClassRegistry

IObjectClassRegistry* GetObjectClassRegistry();

} // namespace OpenRTI
} // namespace Mom
