# CMake generated Testfile for 
# Source directory: D:/Scratch/OpenRTI-0.9.0/tests/rti1516e/fddget
# Build directory: D:/Scratch/OpenRTI-0.9.0/tests/rti1516e/fddget
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rti1516e/fddget-1516e-1 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-1.xml" "-o" "HLAobjectRoot" "-a" "HLAprivilegeToDeleteObject" "-i" "HLAinteractionRoot")
add_test(rti1516e/fddget-1516e-2 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-1.xml" "-o" "ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-i" "InteractionClass1" "-p" "Parameter1")
add_test(rti1516e/fddget-1516e-3 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-1.xml" "-o" "HLAobjectRoot.ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "HLAobjectRoot.ObjectClass1.Attribute1" "-i" "HLAinteractionRoot.InteractionClass1" "-p" "HLAinteractionRoot.InteractionClass1.Parameter1")
add_test(rti1516e/fddget-1516e-4 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-1.xml" "-o" "ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-a" "Attribute2" "-i" "InteractionClass2" "-p" "Parameter1" "-p" "Parameter2")
add_test(rti1516e/fddget-1516e-5 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-1.xml" "-o" "HLAobjectRoot.ObjectClass1.ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "HLAobjectRoot.ObjectClass1.Attribute1" "-a" "HLAobjectRoot.ObjectClass1.ObjectClass2.Attribute2" "-i" "HLAinteractionRoot.InteractionClass1.InteractionClass2" "-p" "HLAinteractionRoot.InteractionClass1.Parameter1" "-p" "HLAinteractionRoot.InteractionClass1.InteractionClass2.Parameter2")
add_test(rti1516e/fddget-1516e-6 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-1.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
add_test(rti1516e/fddget-1516e-7 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-1.xml" "-o" "HLAobjectRoot.ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "HLAobjectRoot.ObjectClass3.Attribute3" "-i" "HLAinteractionRoot.InteractionClass3" "-p" "HLAinteractionRoot.InteractionClass3.Parameter3")
add_test(rti1516e/fddget-1516e-11 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "HLAobjectRoot" "-a" "HLAprivilegeToDeleteObject" "-i" "HLAinteractionRoot")
add_test(rti1516e/fddget-1516e-12 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-i" "InteractionClass1" "-p" "Parameter1")
add_test(rti1516e/fddget-1516e-13 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "ObjectClass1.Attribute1" "-i" "InteractionClass1" "-p" "InteractionClass1.Parameter1")
add_test(rti1516e/fddget-1516e-14 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-a" "Attribute2" "-i" "InteractionClass2" "-p" "Parameter1" "-p" "Parameter2")
add_test(rti1516e/fddget-1516e-15 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "ObjectClass1.ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "ObjectClass1.Attribute1" "-a" "ObjectClass1.ObjectClass2.Attribute2" "-i" "InteractionClass1.InteractionClass2" "-p" "InteractionClass1.Parameter1" "-p" "InteractionClass1.InteractionClass2.Parameter2")
add_test(rti1516e/fddget-1516e-16 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
add_test(rti1516e/fddget-1516e-17 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "ObjectClass3.Attribute3" "-i" "InteractionClass3" "-p" "InteractionClass3.Parameter3")
add_test(rti1516e/fddget-1516e-20 "${CTEST_BINARY_DIRECTORY}/fddget-1516e" "-D" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516e/fddget/fdd-2.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
