// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FOMCodeGen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class FOMEncodingImpl : FOMEncodingImplBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n// Code automatically generated from ");
            
            #line 7 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FOM.Filename));
            
            #line default
            #line hidden
            this.Write(", do not edit\r\n\r\n#pragma once\r\n\r\n#include <vector>\r\n#include <cstring>\r\n\r\n#includ" +
                    "e \"RTI/encoding/BasicDataElements.h\"\r\n#include \"RTI/encoding/HLAfixedRecord.h\"\r\n" +
                    "#include \"RTI/encoding/HLAfixedArray.h\"\r\n#include \"RTI/encoding/HLAvariableArray" +
                    ".h\"\r\n");
            
            #line 18 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FOM.PredefinedTypeIncludes));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 19 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (FOM.UsePrecompiledHeaders) { 
            
            #line default
            #line hidden
            this.Write("#include \"stdafx.h\"\r\n");
            
            #line 21 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
}
            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 22 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EncodingHeaderFilename));
            
            #line default
            #line hidden
            this.Write("\"\r\n\r\n");
            
            #line 24 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 foreach (var namespacePart in FOM.Namespace) { 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 25 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespacePart));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 26 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 28 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FOM.EncodingForwardDeclarations));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 30 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"

foreach (var dataType in FOM.DataTypes.Values)
{
  if (dataType is FOMParser.FixedRecordDataType && dataType.Generate)
  {
    var fixedRecordDataType = dataType as FOMParser.FixedRecordDataType;
    if (dataType.Comment != null && dataType.Comment != "")
    {
            
            #line default
            #line hidden
            
            #line 38 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 39 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            
            #line 40 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 40 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding() : rti1516e::HLAfixedRecord(");
            
            #line 40 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedRecordDataType.Version));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 42 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"

    foreach (var field in fixedRecordDataType.AllFields)
    {

            
            #line default
            #line hidden
            this.Write("  rti1516e::HLAfixedRecord::appendElementPointer(&m");
            
            #line 46 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 46 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Version));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 47 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"

    } // foreach fixedRecordDataType.Fields

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 51 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::~");
            
            #line 51 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding()\r\n{\r\n}\r\nuint32_t ");
            
            #line 54 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::getVersion() const { return rti1516e::HLAfixedRecord::getVersion(); }\r\n" +
                    "");
            
            #line 55 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 foreach (var field in fixedRecordDataType.AllFields) { 
            
            #line default
            #line hidden
            this.Write("void ");
            
            #line 56 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::Set");
            
            #line 56 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 56 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" value)\r\n{\r\n");
            
            #line 58 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  if (field.DataType is FOMParser.BasicDataRepresentation || field.DataType is FOMParser.SimpleDataType || field.DataType is FOMParser.ArrayDataType)
    { 
            
            #line default
            #line hidden
            this.Write("\tm");
            
            #line 60 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(".set(value);\r\n");
            
            #line 61 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("\tm");
            
            #line 62 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 63 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 65 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (field.DataType is FOMParser.ArrayDataType) {
     var arrayDataType = field.DataType as FOMParser.ArrayDataType;

            
            #line default
            #line hidden
            this.Write("void ");
            
            #line 68 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::Set");
            
            #line 68 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("(const ");
            
            #line 68 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayDataType.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write("* value, size_t size)\r\n{\r\n\tm");
            
            #line 70 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(".set(value, size);\r\n}\r\n");
            
            #line 72 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } 
            
            #line default
            #line hidden
            
            #line 73 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 73 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::Get");
            
            #line 73 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("() const\r\n{\r\n");
            
            #line 75 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (field.Version > 0) { 
            
            #line default
            #line hidden
            this.Write("  if (getVersion() < ");
            
            #line 76 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Version));
            
            #line default
            #line hidden
            this.Write(")\r\n  {\r\n    throw rti1516e::EncoderException(L\"field \\\"");
            
            #line 78 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\\\" is not available in decoded record version \" + std::to_wstring(getVersion()));" +
                    "\r\n  }\r\n");
            
            #line 80 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } 
            
            #line default
            #line hidden
            
            #line 81 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (field.DataType is FOMParser.EnumeratedDataType) { 
            
            #line default
            #line hidden
            this.Write("  return static_cast<");
            
            #line 82 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write(">(m");
            
            #line 82 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(".get());\r\n");
            
            #line 83 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } else if (field.DataType is FOMParser.BasicDataRepresentation || field.DataType is FOMParser.SimpleDataType || field.DataType is FOMParser.ArrayDataType) { 
            
            #line default
            #line hidden
            this.Write("  return m");
            
            #line 84 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(".get();\r\n");
            
            #line 85 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } else {
            
            #line default
            #line hidden
            this.Write("  return m");
            
            #line 86 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 87 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } // else (field.DataType is FOMParser.EnumeratedDataType) 
            
            #line default
            #line hidden
            this.Write("}\r\nbool ");
            
            #line 89 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::Is");
            
            #line 89 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("Available() const\r\n{\r\n");
            
            #line 91 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (field.Version > 0) { 
            
            #line default
            #line hidden
            this.Write("  return (getVersion() >= ");
            
            #line 92 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Version));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 93 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("  return true;\r\n");
            
            #line 95 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 97 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 } // foreach fixedRecordDataType.Fields 
            
            #line default
            #line hidden
            
            #line 98 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"

  } // if (dataType is FOMParser.FixedRecordDataType)
  else if (dataType is FOMParser.FixedArrayDataType && dataType.Generate)
  {
    var fixedArrayDataType = dataType as FOMParser.FixedArrayDataType;
    var elementDataType = fixedArrayDataType.DataType;
    int cardinality = Int32.Parse(fixedArrayDataType.Cardinality);
    if (dataType.Comment != null && dataType.Comment != "")
    {
            
            #line default
            #line hidden
            
            #line 107 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 108 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("// fixed array of ");
            
            #line 109 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.DataType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 110 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  if (elementDataType is FOMParser.BasicDataRepresentation || elementDataType is FOMParser.SimpleDataType)
    { // array of simple or basic types: access data by reference/pointer

            
            #line default
            #line hidden
            
            #line 113 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 113 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding()\r\n  : HLAfixedArray(");
            
            #line 114 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("(), ");
            
            #line 114 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 115 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (cardinality > 0) {
            
            #line default
            #line hidden
            this.Write("  , mData(");
            
            #line 116 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cardinality));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 117 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 119 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (cardinality > 0) {
            
            #line default
            #line hidden
            this.Write("  for (int i=0; i < ");
            
            #line 120 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cardinality));
            
            #line default
            #line hidden
            this.Write("; i++)\r\n  {\r\n    mEncoding[i].setDataPointer(&mData[i]);\r\n    setElementPointer(i" +
                    ", &mEncoding[i]);\r\n  }\r\n");
            
            #line 125 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 127 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (cardinality > 0) {
            
            #line default
            #line hidden
            
            #line 128 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 128 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding(");
            
            #line 128 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data)\r\n  : HLAfixedArray(");
            
            #line 129 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("(), ");
            
            #line 129 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(")\r\n  , mData(");
            
            #line 130 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n  set(data.data(), data.size());\r\n  for (int i=0;i<");
            
            #line 133 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(";i++)\r\n  {\r\n    mEncoding[i].setDataPointer(&mData[i]);\r\n    setElementPointer(i," +
                    " &mEncoding[i]);\r\n  }\r\n}\r\nvoid ");
            
            #line 139 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(");
            
            #line 139 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data) {\r\n  set(data.data(), data.size());\r\n}\r\nvoid ");
            
            #line 142 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(const ");
            
            #line 142 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write("* data, size_t size) \r\n{\r\n  if (size <= ");
            
            #line 144 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(") {\r\n    memcpy(mData.data(), data, size);\r\n  } else {\r\n    memcpy(mData.data(), " +
                    "data, ");
            
            #line 147 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(");\r\n  }\r\n}\r\n");
            
            #line 150 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 150 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::get() const\r\n{\r\n  return mData;\r\n}\r\n");
            
            #line 154 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            
            #line 155 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } else {  // array of complex type 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 156 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 156 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding()\r\n      : HLAfixedArray(");
            
            #line 157 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("(), ");
            
            #line 157 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n");
            
            #line 159 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (cardinality > 0) {
            
            #line default
            #line hidden
            this.Write("      for (int i=0; i < ");
            
            #line 160 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cardinality));
            
            #line default
            #line hidden
            this.Write("; i++)\r\n      {\r\n        mEncoding[i] = mData[i];\r\n        setElementPointer(i, &" +
                    "mEncoding[i]);\r\n      }\r\n");
            
            #line 165 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 167 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
 if (cardinality > 0) {
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 168 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 168 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding(");
            
            #line 168 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data)\r\n      : HLAfixedArray(");
            
            #line 169 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("(), ");
            
            #line 169 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(")\r\n      , mData(");
            
            #line 170 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      set(data.data(), data.size());\r\n      for (int i=0;i<");
            
            #line 173 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(";i++)\r\n      {\r\n        mEncoding[i].setDataPointer(&mData[i]);\r\n        setEleme" +
                    "ntPointer(i, &mEncoding[i]);\r\n      }\r\n    }\r\n    void ");
            
            #line 179 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(");
            
            #line 179 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data) {\r\n      set(data.data(), data.size());\r\n    }\r\n    void ");
            
            #line 182 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(const ");
            
            #line 182 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write("* data, size_t size) \r\n    {\r\n      if (size <= ");
            
            #line 184 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(") {\r\n        memcpy(mData.data(), data, size);\r\n      } else {\r\n        memcpy(mD" +
                    "ata.data(), data, ");
            
            #line 187 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Cardinality));
            
            #line default
            #line hidden
            this.Write(");\r\n      }\r\n    }\r\n    ");
            
            #line 190 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 190 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fixedArrayDataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::get() const\r\n    {\r\n      return mData;\r\n    }\r\n");
            
            #line 194 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            
            #line 195 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } // if (elementDataType is FOMParser.BasicDataRepresentation || elementDataType is FOMParser.SimpleDataType)
  }  // if (dataType is FOMParser.FixedArrayDataType)
  else if (dataType is FOMParser.VariableArrayDataType && dataType.Generate)
  {
    var variableArrayDataType = dataType as FOMParser.VariableArrayDataType;
    var elementDataType = variableArrayDataType.DataType;
    if (dataType.Comment != null && dataType.Comment != "")
    {
            
            #line default
            #line hidden
            
            #line 203 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 204 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("// variable array of ");
            
            #line 205 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 206 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  if (elementDataType is FOMParser.BasicDataRepresentation || elementDataType is FOMParser.SimpleDataType)
    { // array of simple or basic types: access data by reference/pointer

            
            #line default
            #line hidden
            
            #line 209 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 209 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding()\r\n  : HLAvariableArray(");
            
            #line 210 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("())\r\n  , mData()\r\n{\r\n}\r\n");
            
            #line 214 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 214 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding(");
            
            #line 214 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data)\r\n  : HLAvariableArray(");
            
            #line 215 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("())\r\n  , mData(data)\r\n{\r\n  update();\r\n}\r\nvoid ");
            
            #line 220 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(");
            
            #line 220 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data)\r\n{\r\n  if (mData.size() != data.size()) {\r\n    mData = data;\r\n    update();" +
                    "\r\n  } else {\r\n    memcpy(mData.data(), data.data(), mData.size());\r\n  }\r\n}\r\nvoid" +
                    " ");
            
            #line 229 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(const ");
            
            #line 229 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write("* data, size_t size)\r\n{\r\n  if (mData.size() != size) {\r\n    mData.resize(size);\r\n" +
                    "    update();\r\n  }\r\n  memcpy(mData.data(), data, size);\r\n}\r\n");
            
            #line 237 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 237 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::get() const { return mData; }\r\nvoid ");
            
            #line 238 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::resize(size_t size)\r\n{\r\n  mData.resize(size);\r\n  update();\r\n}\r\n// resiz" +
                    "e buffer and encoder array before actually decoding \r\nsize_t ");
            
            #line 244 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::decodeFrom(const rti1516e::Octet* buffer, size_t bufferSize, size_t ind" +
                    "ex)\r\n{\r\n  size_t newSize = decodedSize(buffer, bufferSize, index);\r\n  resize(new" +
                    "Size);\r\n  return HLAvariableArray::decodeFrom(buffer, bufferSize, index);\r\n}\r\nvo" +
                    "id ");
            
            #line 250 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write(@"Encoding::update()
{
  size_t size = mData.size();
  mEncoding.resize(size);
  for (size_t i=0; i<size; i++)
  {
    mEncoding[i].setDataPointer(&mData.data()[i]);
    if (i < HLAvariableArray::size()) {
      setElementPointer(i, &mEncoding[i]);
    } else {
      addElementPointer(&mEncoding[i]);
    }
  }
}

");
            
            #line 265 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } else {  // array of complex type 
            
            #line default
            #line hidden
            
            #line 266 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 266 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding()\r\n  : HLAvariableArray(");
            
            #line 267 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("())\r\n{\r\n}\r\n");
            
            #line 270 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::");
            
            #line 270 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding(");
            
            #line 270 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data)\r\n  : HLAvariableArray(");
            
            #line 271 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("())\r\n{\r\n  set(data);\r\n}\r\nvoid ");
            
            #line 275 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(");
            
            #line 275 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" data)\r\n{\r\n  clear();\r\n  for (size_t i=0; i < data.size();i++)\r\n  {\r\n    addEleme" +
                    "nt(static_cast<const ");
            
            #line 280 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("&>(data[i]));\r\n  }\r\n}\r\nvoid ");
            
            #line 283 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(std::vector<");
            
            #line 283 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write(">& data)\r\n{\r\n  clear();\r\n  for (size_t i=0; i < data.size();i++)\r\n  {\r\n    addEle" +
                    "mentPointer(static_cast<");
            
            #line 288 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("*>(&data[i]));\r\n  }\r\n}\r\nvoid ");
            
            #line 291 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(const ");
            
            #line 291 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("* data, size_t size)\r\n{\r\n  clear();\r\n  for (size_t i=0; i < size;i++)\r\n  {\r\n    a" +
                    "ddElement(static_cast<const ");
            
            #line 296 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("&>(data[i]));\r\n  }\r\n}\r\nvoid ");
            
            #line 299 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::set(");
            
            #line 299 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("* data, size_t size)\r\n{\r\n  clear();\r\n  for (size_t i=0; i < size;i++)\r\n  {\r\n    a" +
                    "ddElementPointer(static_cast<");
            
            #line 304 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(variableArrayDataType.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write("*>(&data[i]));\r\n  }\r\n}\r\n// resize buffer and encoder array before actually decodi" +
                    "ng \r\nsize_t ");
            
            #line 308 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataType.Name));
            
            #line default
            #line hidden
            this.Write("Encoding::decodeFrom(const rti1516e::Octet* buffer, size_t bufferSize, size_t ind" +
                    "ex)\r\n{\r\n  size_t newSize = decodedSize(buffer, bufferSize, index);\r\n  resize(new" +
                    "Size);\r\n  return HLAvariableArray::decodeFrom(buffer, bufferSize, index);\r\n}\r\n");
            
            #line 314 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"

    } // if (elementDataType is FOMParser.BasicDataRepresentation || elementDataType is FOMParser.SimpleDataType)
  } // if (dataType is FOMParser.VariableArrayDataType)

} // foreach (var dataType in FOM.DataTypes.Values)

            
            #line default
            #line hidden
            
            #line 320 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"

foreach (var namespacePart in FOM.Namespace)
{

            
            #line default
            #line hidden
            this.Write("} // namespace ");
            
            #line 324 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespacePart));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 325 "D:\vfs\CANoe\release\15\Projects_Source\OpenRTI\src\Tools\FOMCodeGen\FOMEncodingImpl.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class FOMEncodingImplBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
