// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FOMCodeGen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class FOMObjectsHeader : FOMObjectsHeaderBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n// Code automatically generated by T4 template from ");
            
            #line 7 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FOM.Filename));
            
            #line default
            #line hidden
            this.Write(@", do not edit
#pragma once

#include <vector>
#include ""RTI/Handle.h""
#include ""RTI/RTIambassador.h""
#include ""RTI/encoding/BasicDataElements.h""
#include ""RTI/encoding/HLAfixedRecord.h""
#include ""RTI/encoding/HLAfixedArray.h""
#include ""RTI/encoding/HLAvariableArray.h""
");
            
            #line 17 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FOM.PredefinedTypeIncludes));
            
            #line default
            #line hidden
            this.Write("\r\n#include \"");
            
            #line 18 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EncodingHeaderFilename));
            
            #line default
            #line hidden
            this.Write("\"\r\n\r\n");
            
            #line 20 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"

foreach (var namespacePart in FOM.Namespace)
{

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 24 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespacePart));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 25 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 27 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 
foreach (var objectClass in FOM.ObjectClasses)
{

            
            #line default
            #line hidden
            this.Write("class ");
            
            #line 31 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write(";\r\nclass ");
            
            #line 32 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass\r\n{\r\n  public:\r\n");
            
            #line 35 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"

  if (objectClass.BaseClass != null)
  {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 39 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass(rti1516ev::RTIambassador* rtiAmbassador, ");
            
            #line 39 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.BaseClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass* baseClass);\r\n\r\n");
            
            #line 41 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } else {
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 42 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass(rti1516ev::RTIambassador* rtiAmbassador);\r\n");
            
            #line 43 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            
            #line 44 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 
  foreach (var attribute in objectClass.Attributes)
  {
    if (attribute.DataType != null)
    {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 49 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 49 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DataType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    rti1516ev::AttributeHandle Get");
            
            #line 50 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("AttributeHandle() const { return m");
            
            #line 50 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("AttributeHandle; }\r\n");
            
            #line 51 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  } else {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 52 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : no data type\r\n");
            
            #line 53 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  
    } // if (attribute.DataType != null)
  } // foreach (var attribute in objectClass.Attributes)

            
            #line default
            #line hidden
            this.Write(@"    void Publish();
    void Unpublish();
    void Subscribe();
    void Unsubscribe();
    void DiscoverObjectInstance (rti1516ev::ObjectInstanceHandle theObject, std::wstring const & theObjectInstanceName);
    void RemoveObjectInstance(rti1516ev::ObjectInstanceHandle theObject);
    rti1516ev::ObjectClassHandle GetObjectClassHandle() const { return mObjectClassHandle; }
    ");
            
            #line 64 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("* GetObjectInstance(const std::wstring& instanceName);\r\n    ");
            
            #line 65 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("* GetObjectInstance(rti1516ev::ObjectInstanceHandle instanceHandle);\r\n    ");
            
            #line 66 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("* CreateObjectInstance(const std::wstring& instanceName);\r\n  private:\r\n    rti151" +
                    "6ev::RTIambassador* mRtiAmbassador;\r\n    // object class handle\r\n    rti1516ev::" +
                    "ObjectClassHandle mObjectClassHandle;\r\n");
            
            #line 71 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 if (objectClass.BaseClass != null) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 72 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.BaseClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass* mBaseClass;\r\n");
            
            #line 73 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    bool mPublished = false;\r\n    bool mSubscribed = false;\r\n    // Attribute han" +
                    "dles\r\n");
            
            #line 77 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 
  foreach (var attribute in objectClass.Attributes)
  {
    if (attribute.DataType != null)
    {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 82 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 82 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DataType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    rti1516ev::AttributeHandle m");
            
            #line 83 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("AttributeHandle;\r\n");
            
            #line 84 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  } else {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 85 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : no data type\r\n");
            
            #line 86 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  
    } // if (attribute.DataType != null)
  } // foreach (var attribute in objectClass.Attributes)

            
            #line default
            #line hidden
            this.Write("  std::map<std::wstring, ");
            
            #line 90 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("*> mObjectInstancesByName;\r\n  std::map<rti1516ev::ObjectInstanceHandle, ");
            
            #line 91 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("*> mObjectInstancesByHandle;\r\n};\r\n\r\nclass ");
            
            #line 94 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            
            #line 94 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"

  if (objectClass.BaseClass != null)
  {

            
            #line default
            #line hidden
            this.Write(" : public ");
            
            #line 97 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.BaseClass.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 98 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } else {

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 101 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } // if 
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 103 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 
  string attributeBitsClass = "uint32_t";
  string attributeBitsPostfix = "";
  if (objectClass.Attributes.Count > 32)
  {
    attributeBitsClass = "uint64_t";
    attributeBitsPostfix = "ull";
  }

            
            #line default
            #line hidden
            this.Write("  public:\r\n    using AttributeBits = ");
            
            #line 113 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributeBitsClass));
            
            #line default
            #line hidden
            this.Write(";\r\n    static const ");
            
            #line 114 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributeBitsClass));
            
            #line default
            #line hidden
            this.Write(" kNone = 0x0;\r\n");
            
            #line 115 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 
  ulong bit = 1;
  foreach (var attribute in objectClass.Attributes)
  {
    if (attribute.DataType != null)
    { 
            
            #line default
            #line hidden
            this.Write("    static const ");
            
            #line 121 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributeBitsClass));
            
            #line default
            #line hidden
            this.Write(" k");
            
            #line 121 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("Bit = 0x");
            
            #line 121 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bit.ToString("X")));
            
            #line default
            #line hidden
            
            #line 121 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributeBitsPostfix));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 122 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
    bit = bit << 1;
    } // if (attribute.DataType != null)
  } // foreach (var attribute in objectClass.Attributes)

            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 127 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n    ");
            
            #line 128 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("(rti1516ev::RTIambassador* ambassador, const std::wstring& instanceName, rti1516e" +
                    "v::ObjectInstanceHandle instanceHandle);\r\n    ~");
            
            #line 129 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n    ");
            
            #line 130 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("(const ");
            
            #line 130 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("&) = delete;\r\n    ");
            
            #line 131 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 131 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("&&) = delete;\r\n    ");
            
            #line 132 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("& operator=(const ");
            
            #line 132 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("&) = delete;\r\n    ");
            
            #line 133 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("& operator=(");
            
            #line 133 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("&&) = delete;\r\n\r\n");
            
            #line 135 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 
  foreach (var attribute in objectClass.Attributes)
  {
    if (attribute.DataType != null)
    {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 140 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 140 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DataType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 141 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DataType.ReturnCppType));
            
            #line default
            #line hidden
            this.Write(" Get");
            
            #line 141 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("() const;\r\n    void Set");
            
            #line 142 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 142 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DataType.CPPType));
            
            #line default
            #line hidden
            this.Write(" newValue);\r\n");
            
            #line 143 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  } else {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 144 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : no data type\r\n");
            
            #line 145 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  
    } // if (attribute.DataType != null)
  } // foreach (var attribute in objectClass.Attributes)

            
            #line default
            #line hidden
            this.Write("     rti1516ev::AttributeHandleValueMap ");
            
            #line 149 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("::GetAllAttributeValues() const;\r\n     rti1516ev::AttributeHandleValueMap GetModi" +
                    "fiedAttributeValues() const;\r\n");
            
            #line 151 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 if (objectClass.HasValidAttributes) { 
            
            #line default
            #line hidden
            this.Write(@"     void UpdateAllAttributeValues();
     void UpdateAllAttributeValues(const rti1516ev::LogicalTime& time);
     void UpdateModifiedAttributeValues();
     void UpdateModifiedAttributeValues(const rti1516ev::LogicalTime& time);
     void ReflectAttributeValues(const rti1516ev::AttributeHandleValueMap& attributes);
");
            
            #line 157 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            this.Write("     AttributeBits getUpdatedAttributes() const { return mLastUpdated; }\r\n\r\n  pro" +
                    "tected:\r\n");
            
            #line 161 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 if (objectClass.HasValidAttributes) { 
            
            #line default
            #line hidden
            this.Write("    void ClearDirtyBits()\r\n    {\r\n");
            
            #line 164 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 if (objectClass.BaseClass != null && objectClass.BaseClass.HasValidAttributes) { 
            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 165 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.BaseClass.Name));
            
            #line default
            #line hidden
            this.Write("::ClearDirtyBits();\r\n");
            
            #line 166 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            this.Write("      mDirty = kNone;\r\n    }\r\n");
            
            #line 169 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
  private:
    // modified by last reflectAttributeValues
    AttributeBits mLastUpdated = kNone;
    // to be sent with next updateAttributes
    AttributeBits mDirty = kNone;
    std::wstring mInstanceName;
    rti1516ev::ObjectInstanceHandle mObjectInstanceHandle;
    rti1516ev::RTIambassador* mRtiAmbassador;
    ");
            
            #line 179 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass* mObjectClass;\r\n    // Attribute value encoders\r\n");
            
            #line 181 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 
  foreach (var attribute in objectClass.Attributes)
  {
    if (attribute.DataType != null)
    {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 186 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 186 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DataType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 187 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DataType.Encoding));
            
            #line default
            #line hidden
            this.Write(" m");
            
            #line 187 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 188 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  } else {

            
            #line default
            #line hidden
            this.Write("    // attribute ");
            
            #line 189 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" : no data type\r\n");
            
            #line 190 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  
    } // if (attribute.DataType != null)
  } // foreach (var attribute in objectClass.Attributes)

            
            #line default
            #line hidden
            this.Write("};\r\n\r\n");
            
            #line 196 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } // foreach (var objectClass in FOM.ObjectClasses) 
            
            #line default
            #line hidden
            this.Write(" \r\n\r\nclass ClassRegistry\r\n{\r\n  public:\r\n    ClassRegistry(rti1516ev::RTIambassado" +
                    "r* rtiAmbassador);\r\n");
            
            #line 202 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 foreach (var objectClass in FOM.ObjectClasses) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 203 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass* get");
            
            #line 203 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass() const { return m");
            
            #line 203 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass.get(); }\r\n");
            
            #line 204 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
    void Initialize();

    void DiscoverObjectInstance(rti1516ev::ObjectInstanceHandle theObject, std::wstring const & theObjectInstanceName);
    void RemoveObjectInstance(rti1516ev::ObjectInstanceHandle theObject);
    void ReflectAttributeValues(rti1516ev::ObjectInstanceHandle theObject, const rti1516ev::AttributeHandleValueMap & attributes);

  private:
    rti1516ev::RTIambassador* mRtiAmbassador;
");
            
            #line 214 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 foreach (var objectClass in FOM.ObjectClasses) { 
            
            #line default
            #line hidden
            this.Write("    std::unique_ptr<");
            
            #line 215 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass> m");
            
            #line 215 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objectClass.Name));
            
            #line default
            #line hidden
            this.Write("ObjectClass;\r\n");
            
            #line 216 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}; // class ClassRegistry\r\n\r\n");
            
            #line 219 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"

foreach (var namespacePart in FOM.Namespace)
{

            
            #line default
            #line hidden
            this.Write("} // namespace ");
            
            #line 223 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespacePart));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 224 "D:\vfs\OpenRTI-codegen\src\Tools\FOMCodeGen\FOMObjectsHeader.tt"
  } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class FOMObjectsHeaderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
