# CMake generated Testfile for 
# Source directory: D:/Scratch/OpenRTI-0.9.0/tests/rti1516/fddget
# Build directory: D:/Scratch/OpenRTI-0.9.0/tests/rti1516/fddget
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rti1516/fddget-1516-1 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-1.xml" "-o" "HLAobjectRoot" "-a" "HLAprivilegeToDeleteObject" "-i" "HLAinteractionRoot")
add_test(rti1516/fddget-1516-2 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-1.xml" "-o" "ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-i" "InteractionClass1" "-p" "Parameter1")
add_test(rti1516/fddget-1516-3 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-1.xml" "-o" "HLAobjectRoot.ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "HLAobjectRoot.ObjectClass1.Attribute1" "-i" "HLAinteractionRoot.InteractionClass1" "-p" "HLAinteractionRoot.InteractionClass1.Parameter1")
add_test(rti1516/fddget-1516-4 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-1.xml" "-o" "ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-a" "Attribute2" "-i" "InteractionClass2" "-p" "Parameter1" "-p" "Parameter2")
add_test(rti1516/fddget-1516-5 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-1.xml" "-o" "HLAobjectRoot.ObjectClass1.ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "HLAobjectRoot.ObjectClass1.Attribute1" "-a" "HLAobjectRoot.ObjectClass1.ObjectClass2.Attribute2" "-i" "HLAinteractionRoot.InteractionClass1.InteractionClass2" "-p" "HLAinteractionRoot.InteractionClass1.Parameter1" "-p" "HLAinteractionRoot.InteractionClass1.InteractionClass2.Parameter2")
add_test(rti1516/fddget-1516-6 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-1.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
add_test(rti1516/fddget-1516-7 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-1.xml" "-o" "HLAobjectRoot.ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "HLAobjectRoot.ObjectClass3.Attribute3" "-i" "HLAinteractionRoot.InteractionClass3" "-p" "HLAinteractionRoot.InteractionClass3.Parameter3")
add_test(rti1516/fddget-1516-11 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "HLAobjectRoot" "-a" "HLAprivilegeToDeleteObject" "-i" "HLAinteractionRoot")
add_test(rti1516/fddget-1516-12 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-i" "InteractionClass1" "-p" "Parameter1")
add_test(rti1516/fddget-1516-13 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "ObjectClass1" "-a" "HLAprivilegeToDeleteObject" "-a" "ObjectClass1.Attribute1" "-i" "InteractionClass1" "-p" "InteractionClass1.Parameter1")
add_test(rti1516/fddget-1516-14 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute1" "-a" "Attribute2" "-i" "InteractionClass2" "-p" "Parameter1" "-p" "Parameter2")
add_test(rti1516/fddget-1516-15 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "ObjectClass1.ObjectClass2" "-a" "HLAprivilegeToDeleteObject" "-a" "ObjectClass1.Attribute1" "-a" "ObjectClass1.ObjectClass2.Attribute2" "-i" "InteractionClass1.InteractionClass2" "-p" "InteractionClass1.Parameter1" "-p" "InteractionClass1.InteractionClass2.Parameter2")
add_test(rti1516/fddget-1516-16 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
add_test(rti1516/fddget-1516-17 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "ObjectClass3.Attribute3" "-i" "InteractionClass3" "-p" "InteractionClass3.Parameter3")
add_test(rti1516/fddget-1516-20 "${CTEST_BINARY_DIRECTORY}/fddget-1516" "-D" "-O" "${CTEST_SOURCE_DIRECTORY}/rti1516/fddget/fdd-2.xml" "-o" "ObjectClass3" "-a" "HLAprivilegeToDeleteObject" "-a" "Attribute3" "-i" "InteractionClass3" "-p" "Parameter3")
